# See LICENSE.vyoma for details

TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

VERILOG_SOURCES = $(PWD)/bcd_to_ex3_buggy.v # provide your design path

TOPLEVEL :=  bcd_ex3_nand # design file
MODULE   :=  test_bcd_to_ex3   # test file

include $(shell cocotb-config --makefiles)/Makefile.sim

clean_all: clean
	rm -rf *.xml sim_build __pycache__ 
